const failure = {
    server_error:{
        "code":400,
        "message":"server_error",
        "status":false
    },
    bad_request:{
        "code":400,
        "message":"bad_request",
        "status":false
    },
    manager_not_found:{
        "code":400,
        "message":"manager_not_found",
        "status":false
    },
    worker_not_found:{
        "code":400,
        "message":"worker_not_found",
        "status":false
    },
    you_must_be_login:{
        "code":400,
        "message":"you_must_be_login",
        "status":false
    },
    worker_already_exist:{
        "code":400,
        "message":"worker_already_exists",
        "status":false
    },
    wrong_password:{
        "code":400,
        "message":"wrong_password",
        "status":false
    },
};
const successfuly = {
    server_error:{
        "code":400,
        "message":"server_error",
        "status":false
    },
    login_successfuly:{
        "code":200,
        "message":"login_successfuly",
        "status":true
    },
    worker_added:{
        "code":200,
        "message":"worker_added",
        "status":true
    },
    task_added:{
        "code":200,
        "message":"task_added",
        "status":true
    },
    task_accepted:{
        "code":200,
        "message":"task_accepted",
        "status":true
    },
    there_is_nothing_to_show:{
        "code":200,
        "message":"there_is_nothing_to_show",
        "status":true
    },
    repots_showing:{
        "code":200,
        "message":"repots_showing",
        "status":true
    },
    task_updated:{
        "code":200,
        "message":"task_updated",
        "status":true
    },
    task_worked:{
        "code":200,
        "message":"task_worked",
        "status":true
    }
}
module.exports = {failure, successfuly};